--------------------------------------------------------
--  파일이 생성됨 - 토요일-5월-23-2020   
--------------------------------------------------------
DROP TABLE "BANZZACK"."ORDERS_TABLE";
DROP TABLE "BANZZACK"."PRODUCT_TABLE";
DROP TABLE "BANZZACK"."REVIEW_TABLE";
DROP TABLE "BANZZACK"."USER_TABLE";
DROP TABLE "BANZZACK"."VIRTUAL_TABLE";
--------------------------------------------------------
--  DDL for Table ORDERS_TABLE
--------------------------------------------------------

  CREATE TABLE "BANZZACK"."ORDERS_TABLE" 
   (	"ORDERS_NUM" NUMBER(7,0), 
	"ORDERS_AMOUNT" NUMBER(3,0), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"PRODUCT_NUM" NUMBER(5,0), 
	"ORDERS_TIME" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BANZZACK"."ORDERS_TABLE"."ORDERS_NUM" IS '주문 번호 PK';
   COMMENT ON COLUMN "BANZZACK"."ORDERS_TABLE"."ORDERS_AMOUNT" IS '주문 수량';
   COMMENT ON COLUMN "BANZZACK"."ORDERS_TABLE"."USER_ID" IS '주문자 아이디 FK';
   COMMENT ON COLUMN "BANZZACK"."ORDERS_TABLE"."PRODUCT_NUM" IS '상품 번호 FK';
   COMMENT ON COLUMN "BANZZACK"."ORDERS_TABLE"."ORDERS_TIME" IS '주문시간';
--------------------------------------------------------
--  DDL for Table PRODUCT_TABLE
--------------------------------------------------------

  CREATE TABLE "BANZZACK"."PRODUCT_TABLE" 
   (	"PRODUCT_NUM" NUMBER(5,0), 
	"PRODUCT_TITLE" VARCHAR2(20 BYTE), 
	"PRODUCT_CATEGORY" VARCHAR2(20 BYTE), 
	"PRODUCT_CONTENTS" VARCHAR2(20 BYTE), 
	"PRODUCT_IMG1" VARCHAR2(20 BYTE), 
	"PRODUCT_IMG2" VARCHAR2(20 BYTE), 
	"PRODUCT_IMG3" VARCHAR2(20 BYTE), 
	"PRODUCT_RPICE" NUMBER(8,0), 
	"PRODUCT_TIME" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_NUM" IS '상품 번호 PK';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_TITLE" IS '상품 제목';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_CATEGORY" IS '상품 카테고리';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_CONTENTS" IS '상품 설명';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_IMG1" IS '상품 이미지1';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_IMG2" IS '상품 이미지2';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_IMG3" IS '상품 이미지3';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_RPICE" IS '상품 가격';
   COMMENT ON COLUMN "BANZZACK"."PRODUCT_TABLE"."PRODUCT_TIME" IS '등록 날짜';
--------------------------------------------------------
--  DDL for Table REVIEW_TABLE
--------------------------------------------------------

  CREATE TABLE "BANZZACK"."REVIEW_TABLE" 
   (	"REVIEW_NUM" NUMBER(6,0), 
	"REVIEW_CONTENTS" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"PRODUCT_NUM" NUMBER(5,0), 
	"REVIEW_TIME" DATE DEFAULT SYSDATE, 
	"REVIEW_IMG" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BANZZACK"."REVIEW_TABLE"."REVIEW_NUM" IS 'COMMENT_NUM ';
   COMMENT ON COLUMN "BANZZACK"."REVIEW_TABLE"."REVIEW_CONTENTS" IS 'COMMENT_CONTENTS ';
   COMMENT ON COLUMN "BANZZACK"."REVIEW_TABLE"."USER_ID" IS 'USER_ID ';
   COMMENT ON COLUMN "BANZZACK"."REVIEW_TABLE"."PRODUCT_NUM" IS 'PRODUCT_NUM ';
   COMMENT ON COLUMN "BANZZACK"."REVIEW_TABLE"."REVIEW_TIME" IS 'COMMENT_TIME ';
   COMMENT ON COLUMN "BANZZACK"."REVIEW_TABLE"."REVIEW_IMG" IS '후기 이미지 경로';
--------------------------------------------------------
--  DDL for Table USER_TABLE
--------------------------------------------------------

  CREATE TABLE "BANZZACK"."USER_TABLE" 
   (	"USER_ID" VARCHAR2(40 BYTE), 
	"USER_PW" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(20 BYTE), 
	"USER_PHONE" VARCHAR2(20 BYTE), 
	"USER_ADDRESS1" VARCHAR2(30 BYTE), 
	"USER_ADDRESS2" VARCHAR2(20 BYTE), 
	"USER_ADDRESS3" VARCHAR2(20 BYTE), 
	"USER_GRANT" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_ID" IS '유저 아이디 PK';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_PW" IS '유저 비밀번호';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_NAME" IS '유저 이름';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_EMAIL" IS '유저 이메일 아이디';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_PHONE" IS '유저번호1';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_ADDRESS1" IS '거주지역';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_ADDRESS2" IS '우편번호';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_ADDRESS3" IS '상세주소';
   COMMENT ON COLUMN "BANZZACK"."USER_TABLE"."USER_GRANT" IS '유저권한 0-일반 1-관리자';
--------------------------------------------------------
--  DDL for Table VIRTUAL_TABLE
--------------------------------------------------------

  CREATE TABLE "BANZZACK"."VIRTUAL_TABLE" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_IMG" VARCHAR2(40 BYTE), 
	"PRODUCT_NUM" NUMBER(5,0), 
	"VIRTUAL_IMG" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BANZZACK"."VIRTUAL_TABLE"."USER_ID" IS '유저 아이디';
   COMMENT ON COLUMN "BANZZACK"."VIRTUAL_TABLE"."USER_IMG" IS '유저가 올린 이미지 경로';
   COMMENT ON COLUMN "BANZZACK"."VIRTUAL_TABLE"."PRODUCT_NUM" IS '상품 번호';
   COMMENT ON COLUMN "BANZZACK"."VIRTUAL_TABLE"."VIRTUAL_IMG" IS '가상착용된 이미지 경로
';
REM INSERTING into BANZZACK.ORDERS_TABLE
SET DEFINE OFF;
REM INSERTING into BANZZACK.PRODUCT_TABLE
SET DEFINE OFF;
REM INSERTING into BANZZACK.REVIEW_TABLE
SET DEFINE OFF;
REM INSERTING into BANZZACK.USER_TABLE
SET DEFINE OFF;
REM INSERTING into BANZZACK.VIRTUAL_TABLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANZZACK"."USER_TABLE_PK" ON "BANZZACK"."USER_TABLE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERS_TABLE
--------------------------------------------------------

  ALTER TABLE "BANZZACK"."ORDERS_TABLE" MODIFY ("ORDERS_TIME" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."ORDERS_TABLE" MODIFY ("PRODUCT_NUM" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."ORDERS_TABLE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."ORDERS_TABLE" MODIFY ("ORDERS_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."ORDERS_TABLE" MODIFY ("ORDERS_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_TABLE
--------------------------------------------------------

  ALTER TABLE "BANZZACK"."PRODUCT_TABLE" MODIFY ("PRODUCT_TIME" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."PRODUCT_TABLE" MODIFY ("PRODUCT_RPICE" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."PRODUCT_TABLE" MODIFY ("PRODUCT_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."PRODUCT_TABLE" MODIFY ("PRODUCT_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."PRODUCT_TABLE" MODIFY ("PRODUCT_TITLE" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."PRODUCT_TABLE" MODIFY ("PRODUCT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW_TABLE
--------------------------------------------------------

  ALTER TABLE "BANZZACK"."REVIEW_TABLE" MODIFY ("PRODUCT_NUM" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."REVIEW_TABLE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."REVIEW_TABLE" MODIFY ("REVIEW_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."REVIEW_TABLE" MODIFY ("REVIEW_NUM" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."REVIEW_TABLE" MODIFY ("REVIEW_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_TABLE
--------------------------------------------------------

  ALTER TABLE "BANZZACK"."USER_TABLE" ADD CONSTRAINT "USER_TABLE_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BANZZACK"."USER_TABLE" MODIFY ("USER_ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."USER_TABLE" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."USER_TABLE" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."USER_TABLE" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."USER_TABLE" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."USER_TABLE" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VIRTUAL_TABLE
--------------------------------------------------------

  ALTER TABLE "BANZZACK"."VIRTUAL_TABLE" MODIFY ("PRODUCT_NUM" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."VIRTUAL_TABLE" MODIFY ("USER_IMG" NOT NULL ENABLE);
  ALTER TABLE "BANZZACK"."VIRTUAL_TABLE" MODIFY ("USER_ID" NOT NULL ENABLE);
